% -------------------------------------------------------------------
%  Generated by MATLAB on 5-Jun-2019 11:10:05
%  MATLAB version: 9.5.0.944444 (R2018b)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

A = saveVarsMat.A; % <8671x2 double> too many elements

clear saveVarsMat;
